services:
  backend:
    container_name: backend
    build: ./backend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${BACK_PORT}/api/v1/health || exit 1"] # requires defined healthpoint and curl installed in the container!
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      postgres_db:
        condition: service_healthy
    env_file: .env
    expose:
      - "${BACK_PORT}"
    networks:
      - gp_internal
    restart: always
  postgres_db:
    container_name: postgres_db
    image: postgres:16.4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 10
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_NAME:-goodplays_db}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes: # need to get back to this later to see if this is the best option
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - gp_internal
    restart: always
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - gp_internal
    restart: always

networks:
  gp_internal:
    name: gp_internal
    internal: true
    driver: bridge
